In [1]:
import pandas as pd
import os

In [2]:
base_path = "/kaggle/input/datasets/dimthkiuoanh/nih-chest-xray-data-preprocessing-output"

train_df = pd.read_csv(os.path.join(base_path, "split_train.csv"))
val_df   = pd.read_csv(os.path.join(base_path, "split_val.csv"))
test_df  = pd.read_csv(os.path.join(base_path, "split_test.csv"))

In [3]:
def count_classes(df, name):
    print(f"\n{name}")
    print(df["label"].value_counts())

count_classes(train_df, "TRAIN")
count_classes(val_df, "VAL")
count_classes(test_df, "TEST")

TRAIN
label
NORMAL       42253
PNEUMONIA      225
Name: count, dtype: int64

VAL
label
NORMAL       9054
PNEUMONIA      48
Name: count, dtype: int64

TEST
label
NORMAL       9054
PNEUMONIA      49
Name: count, dtype: int64

In [4]:
summary = pd.DataFrame({
    "Split": ["Train", "Val", "Test"],
    "NORMAL": [
        (train_df["label"] == "NORMAL").sum(),
        (val_df["label"] == "NORMAL").sum(),
        (test_df["label"] == "NORMAL").sum()
    ],
    "PNEUMONIA": [
        (train_df["label"] == "PNEUMONIA").sum(),
        (val_df["label"] == "PNEUMONIA").sum(),
        (test_df["label"] == "PNEUMONIA").sum()
    ]
})

summary["Total"] = summary["NORMAL"] + summary["PNEUMONIA"]
summary

   Split  NORMAL  PNEUMONIA  Total
0  Train   42253        225  42478
1    Val    9054         48   9102
2   Test    9054         49   9103

In [5]:
total = summary["Total"].sum()

summary["Ratio (%)"] = summary["Total"] / total * 100
summary

   Split  NORMAL  PNEUMONIA  Total  Ratio (%)
0  Train   42253        225  42478  69.999835
1    Val    9054         48   9102  14.999258
2   Test    9054         49   9103  15.000906